version: '3'

services:
  userapi:
    image: "{{ env.USERAPI_IMAGE }}"
    restart: always
    ports:
      - 8080:8080
    environment:
      GARNET_SECURITY_HASH_MEMORY: 65536
      GARNET_SECURITY_HASH_ITERATIONS: 3
      GARNET_SECURITY_HASH_PARALLELISM: 4
      GARNET_SECURITY_HASH_SALT_LENGTH: 16
      GARNET_SECURITY_HASH_KEY_LENGTH: 32
      GARNET_SERVER_HTTP_PORT: 8080
      GIN_MODE: release
      GARNET_SECURITY_ENCRYPTION_KEY: "{{ env.GARNET_SECURITY_ENCRYPTION_KEY }}"
      GARNET_SECURITY_ENCRYPTION_IV: "{{ env.GARNET_SECURITY_ENCRYPTION_IV }}"
      GARNET_SECURITY_ENCRYPTION_TOKEN_SECRET: "{{ env.GARNET_SECURITY_ENCRYPTION_TOKEN_SECRET }}"
      GARNET_DATABASE_URL: "{{ env.GARNET_DATABASE_URL }}"
