on:
  push:
    branches: [main]

jobs:
  deploy-yc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.YC_VM_SSH }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.YC_VM_IP }} > ~/.ssh/known_hosts

      - name: Copy docker-compose and script
        run: |
          scp ./docker-compose.yc.yaml scp://${{ secrets.YC_VM_USERNAME }}@${{ secrets.YC_VM_IP }}${{ secrets.YC_VM_WORKDIR }}/docker-compose.yaml
          scp ./scripts/yc-init.sh scp://${{ secrets.YC_VM_USERNAME }}@${{ secrets.YC_VM_IP }}${{ secrets.YC_VM_WORKDIR }}/init.sh

      - name: Pull and restart
        run: |
          ssh ${{ secrets.YC_VM_USERNAME }}@${{ secrets.YC_VM_IP }} \
          'export YC_VM_WORKDIR=${{ secrets.YC_VM_WORKDIR }} && ' \
          'export YC_SECRETS_ID=${{ secrets.YC_SECRETS_ID }} && ' \
          'bash ${{ YC_VM_WORKDIR }}/init.sh'
